### ISSUE TITLE
Settings menu item does not work on Mac app.

### ISSUE THREAD

**Issue by sebfontan** [1943time/inkdown#101]
Settings menu item does not work on Mac app. I can open the Settings menu with the Cmd+, shortcut, but not by using the menubar.
<img width="400" alt="Screenshot 2024-10-12 at 1 41 34 AM" src="https://github.com/user-attachments/assets/37fe3fdf-87ee-4f7b-8a64-905ef7c0993b">

**Comment by 1943time** [comment]
This problem will be fixed in the next version
