### ISSUE TITLE
功能请求：支持 Piclist server上传图片

### ISSUE THREAD

**Issue by Tribbtsz** [1943time/inkdown#106]
### 问题反馈：Inkdown 图片上传功能在服务器端 Piclist Core 部署环境下无法正常工作

**问题描述**：
在使用本地 Piclist 监听的情况下，Inkdown 能够成功配置并上传图片，上传 URL 格式为 `http://127.0.0.1:36677/upload?picbed=local&configName=Default`。然而，当尝试使用部署在服务器上的 Piclist Core 进行图片上传时，尽管服务器端能够接收到图片并返回成功消息，Inkdown 中显示的图片却是一个白板。

**具体表现**：
- 上传 URL 格式为 `http://192.168.1.12:36677/upload?key=hellopiclist`。
- 服务器端返回的消息为 `{"success":true,"result":["http://192.168.1.12:37777/background-image.jpg"]}`（对应图片已经使用 caddy 向外提供）。
- **直接粘贴返回消息中的 URL 可以正常显示图片**。

**问题截图**：
![白板问题截图](https://github.com/user-attachments/assets/b6ac88b3-3809-4c35-b7f5-d745ca20c809)

**期望结果**：
Inkdown 能够正确显示通过服务器端 Piclist Core 上传的图片。

**环境信息**：
- Inkdown 版本：Windows x64 离线版本
- Piclist Core 部署环境：服务器端

### 非常感谢大佬的工作！

**Comment by 1943time** [comment]
这个问题我找时间试试

**Comment by 1943time** [comment]
客户端返回的格式是 
```ts
interface {
     success: boolean
        message?: string
        fullResult: {
          imgUrl: string
      }[]
}
```
而服务端返回的是 

```ts
interface {
  success: boolean,
  result: string[]
}
```

这个格式对不上，Piclist 是因为版本不对改了响应体数据结构么

**Comment by Tribbtsz** [comment]
客户端和服务端测试的时候都是使用的最新版本，似乎是 piclist-core 返回的和客户端本身就是不一样的？[官方说明](https://piclist.cn/advanced.html#%E5%86%85%E7%BD%AEserver%E7%9A%84%E4%BD%BF%E7%94%A8)中的返回格式是后者，虽然我又测试了一次本地客户端是可以的。

另外，我在一篇[博客](https://www.lvbibir.cn/posts/blog/docker-deploy-piclist/#12-nginx-%E9%85%8D%E7%BD%AE)中看到关于在Obsidian笔记软件中使用服务器部署的 piclist-core 的时候，作者注明了要开启服务器模式，似乎就是为了区别：![Obsidian中配置服务器部署的piclist](https://image.lvbibir.cn/blog/image-20231229-155939.png)![image](https://github.com/user-attachments/assets/a0e1c273-fc26-4a3c-a395-7a3f40b3c492)

**Comment by 1943time** [comment]
我在下个版本会尝试修复这个问题，不过下个版本估计还会等一段时间，最近不会发布。不好意思~

**Comment by Tribbtsz** [comment]
好的，非常感谢大佬！

**Comment by 1943time** [comment]
我在新版兼容了这种返回格式，你可以试试

**Comment by Tribbtsz** [comment]
已经可以了，感谢大佬的工作！
