### ISSUE TITLE
Enhancements for a More Efficient and User-Friendly Web Editor

### ISSUE THREAD

**Issue by bolavefasfas** [1943time/inkdown#78]
This is an insane project Love it !!
# Feature Request

I hope this message finds you well. I am writing to suggest several improvements to our web editor, aiming to enhance its usability and functionality.

1. **Code Block Text Wrapping**: Currently, the code block text does not wrap in our Bluestone web editor 
![image](https://github.com/1943time/bluestone/assets/82230241/05d11167-d7a8-426f-8f5d-55c3d8fd8f27)

 It would be beneficial to implement a feature that allows the text to wrap and display as demonstrated in 
![image](https://github.com/1943time/bluestone/assets/82230241/06c7693e-b44d-46ef-abdf-22382fc57c3e)

2. **Eliminate Excessive Spacing**: There are instances where the editor contains too much space 
![image](https://github.com/1943time/bluestone/assets/82230241/f244afc8-834e-41b5-8b87-d13fee2607b3). Reducing this would provide a cleaner and more professional look.

3. **Automatic Markdown Formatting**: When markdown is pasted into the editor, it does not automatically adopt the markdown format 
![image](https://github.com/1943time/bluestone/assets/82230241/37965cc7-3763-4d6d-8153-f07bc2074f7a)
 and 
![image](https://github.com/1943time/bluestone/assets/82230241/374a3f28-9972-419e-b629-8e7c05eb38a0)

. This feature would greatly improve efficiency, especially when pasting code blocks or headings 
![image](https://github.com/1943time/bluestone/assets/82230241/24994db7-7fba-4f75-99a4-907c82ad2e65)

    For example, pasting the following code should automatically format it as a bash code block:

    ```bash
    go build -tags nogcs,nos3,nosqlite -ldflags "-s -w -X github.com/drakkan/sftpgo/v2/internal/version.commit=`git describe --always --abbrev=8 --dirty` -X github.com/drakkan/sftpgo/v2/internal/version.date=`date -u +%FT%TZ`" -o sftpgo
    ```

4. **Add Copy Button for Code Blocks**: A dedicated copy button for code blocks would make it easier for users to copy the code (see ![image](https://github.com/1943time/bluestone/assets/82230241/77f86468-5af4-4fd3-a18b-8d8db1a05f75)

5. **Add an Index Sidebar**: An index sidebar would help users navigate through the document more efficiently 
![image](https://github.com/1943time/bluestone/assets/82230241/22a69da9-0437-4066-8aeb-b130d9012fb9)

6. **Ability to Add Subpages**: It would be useful to have the ability to add subpages using the "/page" feature, similar to editors like Notion 
![image](https://github.com/1943time/bluestone/assets/82230241/ed8e5407-5e02-479e-b885-3feab2badaa8), Anytype, Capacities, Affine 
![image](https://github.com/1943time/bluestone/assets/82230241/cdb5fb48-f558-4898-8c7c-bed4337c7212), and Outline. This feature would allow users to create notes on the go without needing to navigate to the folder, create a note, and link it.
No need for folder just notes instide notes.

7. **Location of Notes Files (.md files)**: To help users set up a backup using a cron job, please provide the default location of notes files (.md files) in both the web-based Linux deployment and the Docker deployment.

8. **Importing notes with multiple folder** inside notes like folder 1 10 notes in it then a folder inside the 1 st folder named folder 2 and few notes inside them. (currently this cannot be imported.)
---
### For clarity, I would appreciate responses in the following format:

1. Feature request accepted
2. Accepted and will be worked on in the next quarter
3. Will not do because ...

This format will help me understand which features will be prioritized and worked on. Implementing these features will elevate the project to a new level, making it more competitive and user-friendly.

Thank you for considering these suggestions. I believe these enhancements will significantly improve the user experience and overall functionality of our web editor.

**Comment by 1943time** [comment]
Thank you for your suggestion

1. Accepted, will be added in 2 versions
2. You may have accidentally created two lists while editing, instead of multiple list items under one list. You can merge them by dragging and dropping them
3. By default, pasting will automatically parse into HTML, but you can use `cmd+option+v` to paste the markdown code, as shown in the shortcut operations in the right column
4. The copy button will pop up when clicking on the language in the upper right corner of the code bar, and it may require a second operation
   <img width="894" alt="image" src=“ https://github.com/1943time/bluestone/assets/115093678/137c0066-5305-45cf-b577-0722f9ccc421 ">
5. What is the difference between this feature and the existing outline function? I think turning on the display outline should meet this requirement
6. inkdown needs to maintain seamless conversion with the file system, and how to convert sub pages to and from the file system is a difficult problem to handle, so this feature cannot be added
7. Synchronize server markdown will bring more development costs, and there are currently no plans to add this feature. However, in the future, it may support the use of MySQL or PostgreSQL storage. You can backup database files, and also consider using the Chrome file system to write documents to the local machine in real time.
8. I haven't reproduced this issue yet. If possible, could you provide an import sample for me to test?


I am currently not maintaining this project full-time, so many features cannot be developed so quickly. Please understand

**Comment by bolavefasfas** [comment]
> Thank you for your suggestion
> 
> 1. Accepted, will be added in 2 versions
> 2. You may have accidentally created two lists while editing, instead of multiple list items under one list. You can merge them by dragging and dropping them
> 3. By default, pasting will automatically parse into HTML, but you can use `cmd+option+v` to paste the markdown code, as shown in the shortcut operations in the right column
> 4. The copy button will pop up when clicking on the language in the upper right corner of the code bar, and it may require a second operation
>    <img width="894" alt="image" src=“ https://github.com/1943time/bluestone/assets/115093678/137c0066-5305-45cf-b577-0722f9ccc421 ">
> 5. What is the difference between this feature and the existing outline function? I think turning on the display outline should meet this requirement
> 6. inkdown needs to maintain seamless conversion with the file system, and how to convert sub pages to and from the file system is a difficult problem to handle, so this feature cannot be added
> 7. Synchronize server markdown will bring more development costs, and there are currently no plans to add this feature. However, in the future, it may support the use of MySQL or PostgreSQL storage. You can backup database files, and also consider using the Chrome file system to write documents to the local machine in real time.
> 8. I haven't reproduced this issue yet. If possible, could you provide an import sample for me to test?
> 
> I am currently not maintaining this project full-time, so many features cannot be developed so quickly. Please understand

1. Thanks 
2.  They are separate list even though spacing is a lot 
3.  Still havent figured out 

---
4. ![image](https://github.com/1943time/bluestone/assets/82230241/88f862ce-3ee0-424b-857c-e1eb31e95da1)
can you keep copy button on 1st and the type like shell or yml or python under dropdown or on the left side as all major platofrom does keep the language on left and copy button on right its standard please and more convinient rather than clicking dropdown then copything.
5. Thanks a lot, its the same found it.
6. Will tell in detail on how to achive it
7. No I am not asking for sync, example: If we use standalone application on windows or os then it will read markdwon and edit and save them to a directory right - I want to know this directory for the web editor [so I can copy these dir using cronjobfor backups (I will setup cron)] Just need the dir where web editor save notes 
8. I will update this post with video 
9. For 66401 words 430197 characters the ui lags a bit can we do something about it ?
10. A button on published page to save as pdf and download markdown file.

**Comment by 1943time** [comment]
3 Through a video demonstration
    
https://github.com/1943time/bluestone/assets/115093678/bde8724d-5c32-4167-91be-7f4ddf7614d9

7 Inkdown web version is stored in sqlite as formatted data, not directly in markdown format, so this cannot be achieved temporarily
9 Having too much code fence may have a significant impact on performance, and solving performance issues with long texts is not easy. As there is still a lot of work to be done, I can only look for optimization opportunities in the future

Other detailed features will be considered for inclusion in future versions

**Comment by 1943time** [comment]
Due to my personal energy not being able to support too much version maintenance, Sorry for the suspension of maintenance for the private deployment version.
