### ISSUE TITLE
Feature Request: Creation Going Forward

### ISSUE THREAD

**Issue by everythingability** [1943time/inkdown#84]
Hello. I can't believe Inkdown doesn't do this. (Apologies if it does)

If you create a link to a file that isn't there, when I click it, CREATE THE FILE. I don't want to have to go somewhere else to create it, then come back. Sometimes I might want to "rough out" lots of links, filling them in (ie. creating pages and adding text) later.

The docs say something about mod+click... Can't get that to do anything (tried command, and command-option and control-click...)

Thanks you

**Comment by 1943time** [comment]
Inkdow does not have this feature currently, I will consider adding it to the next version if it does not affect the existing architecture.

**Comment by 1943time** [comment]
In the new version, if a non-existent link is filled in, when using `cmd+click'`to open it, it will ask whether to create it

<img width="398" alt="image" src="https://github.com/1943time/inkdown/assets/115093678/f7c31146-4f1f-4c77-b2c1-768a7d9e1b6c">

The link needs to use a relative path `./` or `../` start

**Comment by everythingability** [comment]
Hi,

ah... lovely thank you. I re-downloaded version 1.0 and still have the same
issue though.

https://youtu.be/b_sPL79qm7g

Tom

**Comment by 1943time** [comment]
Has the workspace been opened? Still only opened a single file, I didn't do any processing under the single file.

The jump handling of a single file may be added in the next version~

**Comment by everythingability** [comment]
Ah... it was a single file.

I just tried a Workspace and it worked PERFECTLY... Thank you very much.

Tom
