### ISSUE TITLE
Should the app be also named as `bluestone`?

### ISSUE THREAD

**Issue by chenrui333** [1943time/inkdown#86]
👋 I am trying to help [packaging this project into homebrew-cask](https://github.com/Homebrew/homebrew-cask/pull/176864), and noticed some inconsistency between the repo name and product name. Would it make sense to also rename the app name to `bluestone` as well? Thanks!

**Comment by 1943time** [comment]
Recently, I did rename Bluestone as Inkdown because I don't use homebrew-cask to install the software, so I'm not sure about the specific reasons for the conflict. I will take some time to take a look later.

**Comment by chenrui333** [comment]
yeah, totally, it is just the renaming thing that matters in here (the app is with inkdown, while the repo is with bluestone, maybe rename the repo to inkdown as well?)

**Comment by 1943time** [comment]
If changing url to inkdow can solve this problem, I can modify it

**Comment by chenrui333** [comment]
yeah, that would be great 💯

**Comment by chenrui333** [comment]
if possible, can you do a new release for the artifact as well?

![image](https://github.com/1943time/inkdown/assets/1580956/0cc8e5c3-92f8-4dd7-9980-fcdba8dd2acb)

**Comment by 1943time** [comment]
Do new artifact need to start with Inkdown-?

**Comment by chenrui333** [comment]
yeah, it should, thanks!
