### ISSUE TITLE
Add CLI option to directly invoke with file name as parameter

### ISSUE THREAD

**Issue by nkiesel** [1943time/inkdown#93]
I would like t be able to invoke the app with a filename instead of having to use the app menu to select a file.

**Comment by 1943time** [comment]
Inkdown currently does not support using cli to open folders, but when an application is already open, system commands can be used to open a single markdown file. For example, on a Mac system:

`open -a "Inkdown" ~/Documents/Untitled.md`

Opening it for the first time may not work, perhaps the next version will correct it.

**Comment by 1943time** [comment]
Fixed in v1.1.0
