### ISSUE TITLE
在随便一个*.md文件点右键，选择inkdown打开，无法打开，一直显示白屏幕

### ISSUE THREAD

**Issue by liuts** [1943time/inkdown#95]
在已经打开一个inkdown进程的情况下
在随便一个*.md文件点右键，选择inkdown打开，无法打开，一直显示白屏幕。

另外：
inkdown无法作为关联*.md文件使用

**Comment by 1943time** [comment]
你用的是什么系统呢？我这里可以首次打开 无法关联指定文件 但是不会白屏

**Comment by liuts** [comment]
我用的window11 ，在已经有一个inkdown进程的情况下会白屏。首次打开的时候，无法关联指定的md文件

**Comment by Linchpin-L** [comment]
我也是win11, 即使没有另一个inkdown进程, 确实也无法用"打开方式-inkdown"的形式打开, 设置workspace的情况下就是上次关闭时的状态, 不设置就是白屏

**Comment by 1943time** [comment]
> 我也是win11, 即使没有另一个inkdown进程, 确实也无法用"打开方式-inkdown"的形式打开, 设置workspace的情况下就是上次关闭时的状态, 不设置就是白屏

最近一段时间有点忙，这个问题应该会最近的在下个版本修复。

**Comment by 1943time** [comment]
v1.1.0中已修复
