### ISSUE TITLE
Title handling inconsistent with Github and other markdown viewers

### ISSUE THREAD

**Issue by ww-wolt** [1943time/inkdown#98]
Please improve the document title handling, as this is the only annoying thing of this otherwise amazing app. I am using Inkdown as a way to edit my documentation which is hosted on Github. Unfortunately the title handling of Inkdown doesn't align with Github or any other Markdown Viewer. In Inkdown it always shows the filename of the document as the title of document. However this title is not baked into the markdown file so when I want to provide the title to my Github Readers as well I have to double it which visually looks very bad:

<img width="895" alt="Screenshot 2024-09-19 at 18 56 09" src="https://github.com/user-attachments/assets/5146b3ec-07c4-487e-9c9a-9fe18297d651">

Also in the outline the title appears doubled then. 
  
    
    
So either always bake the filename as a H1 also into the markdown file or let me edit the two separately and make it visually clear that one is the filename and the other one is the document title, for example like this:

<img width="1194" alt="Screenshot 2024-09-19 at 19 10 47" src="https://github.com/user-attachments/assets/9263b4e4-2c4b-480d-a2c0-a82ff9a01d4b">

(for UX reasons the title could might be prefilled with the value from the filename)

Another idea might be an option in application setting to turn off filename showing as title or turn on baking filename as title to file etc. 

Probably there are other good solutions as well but the current state is clearly not optimal.

**Comment by 1943time** [comment]
This form draws inspiration from Obsidian, and modifying this feature would incur high costs. Perhaps a configuration could be added to make the file name appear smaller.

**Comment by ww-wolt** [comment]
Hm I understand if it's technically difficult. But it would be very cool to at least have the simplest option: Title baking.
I assume this wouldn't be to hard technically:

1. Check if title baking option is set in application settings
2. Every time when saving, put filename on top of markdown file as H1

**Comment by 1943time** [comment]
In 1.2.0, the file name can be displayed in a smaller size.
